version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "example"
    volumes:
      - /data
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "example"
  app:
    build: ./app
    ports:
      - 80:8080
  inventory:
    build: ./inventory
    ports:
      - 8082:8080
    depends_on:
      - "mongo"
    links:
      - "mongo"
